const align = 'center'

const columns = {
    PURCHASE_HISTORY: [
        {   title:  'Date', dataIndex: 'createdAt', align    },
        {   title:  'Purchase ID', dataIndex: 'pur_id', align     },
        {   title:  'User Account Number', dataIndex: 'user_acc_num', align    }, 
        {   title:  'Number of Tokens', dataIndex: 'num_of_token', align    },
        {   title:  'Token Price', dataIndex: 'token_price', align    },
        {   title:  'Total', dataIndex: 'total_price', align    },
        {   title:  'Status', dataIndex: 'status', align    },
    ],
    SELLING_HISTORY: [
        {   title:  'Date', dataIndex: 'date', align    },
        {   title:  'Selling ID', dataIndex: 'sell_id', align     },
        {   title:  'User Account Number', dataIndex: 'user_acc_num', align    }, 
        {   title:  'Number of Tokens', dataIndex: 'num_of_tokens', align    },
        {   title:  'Token Price', dataIndex: 'token_price', align    },
        {   title:  'Total', dataIndex: 'total_price', align    },
        {   title:  'Status', dataIndex: 'status', align    },
    ],
    WITHDRAWAL_HISTORY: [
        {   title:  'Request Number', dataIndex: 'request_number', align     },
        {   title:  'Date', dataIndex: 'createdAt', align    },
        {   title:  'Name', dataIndex: 'name', align    }, 
        {   title:  'UPI', dataIndex: 'UPI', align    },
        {   title:  'Bank Account Number', dataIndex: 'BankAccountNumber', align    },
        {   title:  'IFSC Code', dataIndex: 'IFSC', align    },
        {   title:  'Total Amount', dataIndex: 'total_amount', align    },
    ],
    CONTACT_HISTORY: [
        {   title:  'Request Number', dataIndex: 'request_number', align     },
        {   title:  'Date', dataIndex: 'createdAt', align    },
        {   title:  'Full Name', dataIndex: 'name', align    }, 
        {   title:  'Account Number', dataIndex: 'account_number', align    },
        {   title:  'Message', dataIndex: 'message', align    },
        {   title:  'Status', dataIndex: 'status', align, style: { backgroundColor: '#6ae657', color: 'white' }    },
    ],
    TOKEN_PRICE_HISTORY: [
        {   title:  'Month + Year', dataIndex: 'month', align     },
        {   title:  'Upload Date', dataIndex: 'date', align    },
        {   title:  'Total Revenue', dataIndex: 'revenue', align    }, 
        {   title:  'Operating Expenses', dataIndex: 'expenses', align    },
        {   title:  'Interest and tax', dataIndex: 'interest', align    },
        {   title:  '15% Service Fee', dataIndex: 'service_fee', align    },
        {   title:  'Net Profit', dataIndex: 'profit', align    },
        {   title:  'Total Tokens', dataIndex: 'total_tokens', align    },
        {   title:  'Token Price', dataIndex: 'token_price', align    },
    ],
    WITHDRAWAL_REQUEST: [
        {   title:  'Date', dataIndex: 'createdAt', align    },
        {   title:  'User ID', dataIndex: 'userId', align     },
        {   title:  'Withdraw ID', dataIndex: 'withdraw_id', align    },
        {   title:  'Account Holder Name', dataIndex: 'acc_holder_name', align    },
        {   title:  'Bank Account Number', dataIndex: 'BankAccountNumber', align    },
        {   title:  'IFSC Code', dataIndex: 'IFSC', align    },
        {   title:  'Total Withdrawal Amount', dataIndex: 'total_amount', align    },
    ],
    CONTACT_REQUEST: [
        {   title:  'Date', dataIndex: 'createdAt', align    },
        {   title:  'Account Number', dataIndex: 'account_number', align    },
        {   title:  'Full Name', dataIndex: 'name', align    }, 
        {   title:  'Email Address', dataIndex: 'email', align    },
        {   title:  'Message', dataIndex: 'message', align    },
    ],
    USER_LIST: [
        {   title:  'User ID', dataIndex: '_id', align     },
        {   title:  'Join Date', dataIndex: 'createdAt', align    },
        {   title:  'Full Name', dataIndex: 'name', align    },
        {   title:  'Phone Number', dataIndex: 'mobileNo', align    },
        {   title:  'Gender', dataIndex: 'gender', align    },
        {   title:  'Total Token Purchase', dataIndex: 'tokens', align    },
        {   title:  'Total Dividend Earned', dataIndex: 'total_dividend', align    },
        {   title:  'Account Balance', dataIndex: 'acc_bal', align    },
    ],
    USER_WITHDRAWAL_HISTORY: [
        {   title:  'Date', dataIndex: 'date', align    },
        {   title:  'Bank Account Number', dataIndex: 'account_no', align    },
        {   title:  'UPI', dataIndex: 'upi', align    },
        {   title:  'IFSC Code', dataIndex: 'ifsc', align    },
        {   title:  'Total Amount', dataIndex: 'amount', align    },
        {   title:  'Status', dataIndex: 'status', align    },
    ],
    USER_PURCHASE_HISTORY: [
        {   title:  'Date', dataIndex: 'date', align    },
        {   title:  'Purchase ID', dataIndex: 'purchase_id', align     },
        {   title:  'Number of Tokens', dataIndex: 'no_token', align    },
        {   title:  'Purchase Price', dataIndex: 'price', align    },
        {   title:  'Total Amount', dataIndex: 'total', align    },
        {   title:  'Status', dataIndex: 'status', align    },
    ],
    USER_SELLING_HISTORY: [
        {   title:  'Date', dataIndex: 'date', align    },
        {   title:  'Selling ID', dataIndex: 'selling_id', align     },
        {   title:  'Number of Tokens', dataIndex: 'no_token', align    },
        {   title:  'Sell Price', dataIndex: 'price', align    },
        {   title:  'Total Amount', dataIndex: 'total', align    },
        {   title:  'Status', dataIndex: 'status', align    },
    ],
    USER_DIVIDEND_HISTORY: [
        {   title:  'Date', dataIndex: 'date', align    },
        {   title:  'Number of tokens', dataIndex: 'total_tokens', align    },
        {   title:  'Total value', dataIndex: 'value', align    }, 
        {   title:  'Dividend per token', dataIndex: 'dividend_token', align    },
        {   title:  'Total amount', dataIndex: 'amount', align    },
    ]

}

export default columns